---
title: "TS model summaries"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(drake)
library(dplyr)
library(ggplot2)

## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("drake", "drake-cache.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)

```

```{r load stuff}
loadd(all_models, cache = cache)

model_names <- lapply(as.list(names(all_models)), 
                      FUN = function(model_result_name)
                        return(strsplit(model_result_name, "_")[[1]]))

names(model_names) = 1:length(model_names)
model_names <- bind_rows(model_names) %>%
  t()

model_names <- as.data.frame(model_names) %>%
  select(-V1) %>%
  rename(seed = V2,
         k = V3,
         ncpts = V4,
         cov = V5,
         nit = V6) %>%
  mutate(k = factor(k),
         ncpts = as.factor(ncpts),
         obj_index = row_number(),
         full_name = names(all_models)) %>%
  mutate(k = factor(k, levels = as.character(sort(as.numeric(levels(k))))))

```


### Runtime of TS models (in seconds)
```{r runtime}
runtime <- data.frame(
  full_name = names(all_models),
  runtime = vapply(all_models,
                   FUN = function(model_result)
                     return(model_result$timing$toc["elapsed"] -
                              model_result$timing$tic["elapsed"]),
                   FUN.VALUE = 8),
  row.names = NULL, stringsAsFactors = F)

model_info <- left_join(model_names, runtime, by = "full_name")


runtime_plot <- ggplot(data = model_info, aes(x = nit, y = runtime, color = k)) +
  geom_boxplot() +
  facet_grid(rows = vars(cov), cols = vars(ncpts), switch = "y") +
  theme_bw() +
  scale_color_viridis_d(end = .8)
runtime_plot

```

## AICc of TS models

```{r aicc}
aiccs <- data.frame(
  # aicc = vapply(all_models,
  #               FUN = function(ts_result)
  #                 return(LDATS::AICc(ts_result$ts[[1]])),
  #               FUN.VALUE = 30),
  aic = vapply(all_models,
               FUN = function(ts_result)
                 return(ts_result$ts[[1]]$AIC),
               FUN.VALUE = 30),
  full_name = names(all_models),
  row.names = NULL, stringsAsFactors = F)

model_info <- left_join(model_info, aiccs, by = "full_name")

aic_plot <- ggplot(data = model_info, aes(x = nit, y = aic, color = k)) +
  geom_boxplot() +
  facet_grid(rows = vars(cov), cols = vars(ncpts), switch = "y") +
  theme_bw() +
  scale_color_viridis_d(end = .8)

aic_plot

```